// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hygyfzswdfzzbzrrrdpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5Z3lmenN3ZGZ6emJ6cnJyZHBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzA4MzMsImV4cCI6MjA2ODg0NjgzM30.xWrhECV2WCs0fKekhnKdldfI8BkD7R08Mb6gHTTJMso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});